"""
Application-facing DTOs for deterministic BSI rule-engine decisions.

DTO means Data Transfer Object.

These immutable objects translate detailed domain evidence into stable
structures that can later be consumed by:

- FastAPI endpoints
- Streamlit review screens
- Background processing jobs
- Audit-report generators
- Persistence adapters

The DTO layer does not evaluate rules or make accounting decisions.
It converts authoritative domain results into application-facing data.
"""

from dataclasses import dataclass
from datetime import date, datetime
from decimal import Decimal
from typing import Self
from uuid import UUID

from bsi.domain.rules.engine import RuleEngineResult
from bsi.domain.rules.evaluator import (
    ConditionEvaluation,
    RuleEligibility,
    RuleEvaluation,
)
from bsi.domain.transactions.enums import TransactionDirection


class RuleEngineDTOError(ValueError):
    """Raised when rule-engine evidence cannot be converted safely."""


type SerializedEvidenceValue = str | tuple[str, str] | None


@dataclass(frozen=True, slots=True)
class RuleEligibilityDTO:
    """
    Application-facing rule-eligibility evidence.

    Attributes
    ----------
    status_allows_evaluation:
        Whether the rule lifecycle status allows execution.

    rule_is_complete:
        Whether the rule contains conditions and an output.

    effective_date_matches:
        Whether the transaction falls inside the rule's effective dates.

    scope_matches:
        Whether the rule applies to the transaction context.

    is_eligible:
        Whether all eligibility requirements passed.
    """

    status_allows_evaluation: bool
    rule_is_complete: bool
    effective_date_matches: bool
    scope_matches: bool
    is_eligible: bool

    @classmethod
    def from_domain(
        cls,
        eligibility: RuleEligibility,
    ) -> Self:
        """
        Convert domain eligibility evidence into a DTO.

        Parameters
        ----------
        eligibility:
            Eligibility result produced by the domain evaluator.

        Returns
        -------
        RuleEligibilityDTO
            Immutable application-facing eligibility evidence.

        Raises
        ------
        RuleEngineDTOError
            If eligibility is not a RuleEligibility object.
        """

        if not isinstance(eligibility, RuleEligibility):
            raise RuleEngineDTOError("eligibility must be a RuleEligibility.")

        return cls(
            status_allows_evaluation=(eligibility.status_allows_evaluation),
            rule_is_complete=eligibility.rule_is_complete,
            effective_date_matches=(eligibility.effective_date_matches),
            scope_matches=eligibility.scope_matches,
            is_eligible=eligibility.is_eligible,
        )


@dataclass(frozen=True, slots=True)
class RuleConditionEvaluationDTO:
    """
    Application-facing evidence for one evaluated condition.

    Expected and actual domain values are converted into stable strings.

    Examples
    --------
    Decimal:
        Decimal("125.00") becomes "125.00".

    Date:
        date(2026, 7, 15) becomes "2026-07-15".

    Direction:
        TransactionDirection.PAYMENT becomes "payment".

    BETWEEN:
        Two boundaries become a two-item string tuple.
    """

    field: str
    operator: str
    expected_value: SerializedEvidenceValue
    actual_value: SerializedEvidenceValue
    matched: bool

    @classmethod
    def from_domain(
        cls,
        evaluation: ConditionEvaluation,
    ) -> Self:
        """
        Convert one condition evaluation into a DTO.

        Parameters
        ----------
        evaluation:
            Evidence generated by the deterministic condition evaluator.

        Returns
        -------
        RuleConditionEvaluationDTO
            Serialized condition evidence.

        Raises
        ------
        RuleEngineDTOError
            If evaluation is not a ConditionEvaluation object.
        """

        if not isinstance(evaluation, ConditionEvaluation):
            raise RuleEngineDTOError("evaluation must be a ConditionEvaluation.")

        return cls(
            field=evaluation.condition.field.value,
            operator=evaluation.condition.operator.value,
            expected_value=_serialize_evidence_value(evaluation.condition.value),
            actual_value=_serialize_evidence_value(evaluation.actual_value),
            matched=evaluation.matched,
        )


@dataclass(frozen=True, slots=True)
class RuleEvaluationDTO:
    """
    Application-facing result for one rule considered by the engine.

    This DTO preserves:

    - Rule identity and configuration
    - Eligibility evidence
    - Condition-level evidence
    - Match counts
    - Configured and matched outputs
    """

    rule_id: UUID
    workspace_id: UUID
    rule_name: str
    rule_status: str
    rule_logic: str
    priority: int
    scope_specificity: int
    configured_output_account_id: UUID | None
    matched_output_account_id: UUID | None
    eligibility: RuleEligibilityDTO
    conditions: tuple[RuleConditionEvaluationDTO, ...]
    evaluated_condition_count: int
    matched_condition_count: int
    failed_condition_count: int
    matched: bool

    @classmethod
    def from_domain(
        cls,
        evaluation: RuleEvaluation,
    ) -> Self:
        """
        Convert one domain rule evaluation into an application DTO.

        Parameters
        ----------
        evaluation:
            Authoritative result of evaluating one rule.

        Returns
        -------
        RuleEvaluationDTO
            Immutable application-facing rule evidence.

        Raises
        ------
        RuleEngineDTOError
            If evaluation is not a RuleEvaluation object.
        """

        if not isinstance(evaluation, RuleEvaluation):
            raise RuleEngineDTOError("evaluation must be a RuleEvaluation.")

        return cls(
            rule_id=evaluation.rule.rule_id,
            workspace_id=evaluation.rule.workspace_id,
            rule_name=evaluation.rule.name,
            rule_status=evaluation.rule.status.value,
            rule_logic=evaluation.rule.logic.value,
            priority=evaluation.rule.priority,
            scope_specificity=evaluation.rule.scope_specificity,
            configured_output_account_id=(evaluation.rule.output_account_id),
            matched_output_account_id=evaluation.output_account_id,
            eligibility=RuleEligibilityDTO.from_domain(evaluation.eligibility),
            conditions=tuple(
                RuleConditionEvaluationDTO.from_domain(condition_evaluation)
                for condition_evaluation in evaluation.condition_evaluations
            ),
            evaluated_condition_count=(evaluation.evaluated_condition_count),
            matched_condition_count=(evaluation.matched_condition_count),
            failed_condition_count=(evaluation.failed_condition_count),
            matched=evaluation.matched,
        )


@dataclass(frozen=True, slots=True)
class RuleEngineDecisionDTO:
    """
    Complete application-facing rule-engine decision.

    This is the primary response object that future Streamlit pages,
    FastAPI endpoints, persistence services, and audit exporters consume.
    """

    workspace_id: UUID
    transaction_id: UUID
    status: str
    conflict_kind: str
    can_map: bool
    requires_review: bool
    is_conflict_blocked: bool
    output_account_id: UUID | None
    winning_rule_id: UUID | None
    matched_rule_ids: tuple[UUID, ...]
    top_rule_ids: tuple[UUID, ...]
    evaluated_rule_count: int
    eligible_rule_count: int
    ineligible_rule_count: int
    matched_rule_count: int
    unmatched_eligible_rule_count: int
    decision_message: str
    evaluations: tuple[RuleEvaluationDTO, ...]

    @classmethod
    def from_domain(
        cls,
        result: RuleEngineResult,
    ) -> Self:
        """
        Convert a domain engine result into an application DTO.

        Parameters
        ----------
        result:
            Completed deterministic rule-engine result.

        Returns
        -------
        RuleEngineDecisionDTO
            Application-facing mapping decision and audit evidence.

        Raises
        ------
        RuleEngineDTOError
            If result is not a RuleEngineResult object.
        """

        if not isinstance(result, RuleEngineResult):
            raise RuleEngineDTOError("result must be a RuleEngineResult.")

        return cls(
            workspace_id=result.workspace_id,
            transaction_id=result.transaction_id,
            status=result.status.value,
            conflict_kind=result.conflict_assessment.kind.value,
            can_map=result.can_map,
            requires_review=result.requires_review,
            is_conflict_blocked=result.is_conflict_blocked,
            output_account_id=result.output_account_id,
            winning_rule_id=result.winning_rule_id,
            matched_rule_ids=result.matched_rule_ids,
            top_rule_ids=result.top_rule_ids,
            evaluated_rule_count=result.evaluated_rule_count,
            eligible_rule_count=result.eligible_rule_count,
            ineligible_rule_count=result.ineligible_rule_count,
            matched_rule_count=result.matched_rule_count,
            unmatched_eligible_rule_count=(result.unmatched_eligible_rule_count),
            decision_message=result.decision_message,
            evaluations=tuple(
                RuleEvaluationDTO.from_domain(evaluation)
                for evaluation in result.evaluations
            ),
        )


def _serialize_evidence_value(
    value: object,
) -> SerializedEvidenceValue:
    """
    Convert supported domain evidence into stable application values.

    Parameters
    ----------
    value:
        Domain condition value or actual transaction value.

    Returns
    -------
    SerializedEvidenceValue
        String, two-item string tuple, or None.

    Raises
    ------
    RuleEngineDTOError
        If the value type is unsupported.
    """

    if value is None:
        return None

    if isinstance(value, tuple):
        if len(value) != 2:
            raise RuleEngineDTOError("Tuple evidence must contain exactly two values.")

        lower_value, upper_value = value

        return (
            _serialize_scalar_evidence(lower_value),
            _serialize_scalar_evidence(upper_value),
        )

    return _serialize_scalar_evidence(value)


def _serialize_scalar_evidence(
    value: object,
) -> str:
    """
    Convert one supported scalar domain value into a string.

    TransactionDirection is checked before str because StrEnum values are
    also string instances.
    """

    if isinstance(value, TransactionDirection):
        return value.value

    if isinstance(value, Decimal):
        return format(value, "f")

    if isinstance(value, datetime):
        raise RuleEngineDTOError("Datetime evidence is not supported; use a date.")

    if isinstance(value, date):
        return value.isoformat()

    if isinstance(value, str):
        return value

    raise RuleEngineDTOError(
        f"Unsupported evidence value type: {type(value).__name__}."
    )
